version: '3.8'
services:
  
  db:
    container_name: db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDb
      - MYSQL_ROOT_PASSWORD=123456

    ports:
      - '3305:3306'
    volumes:
      - db:/var/lib/mysql
  
      
volumes:
  db:
    driver: local
